# AnotherRTS fallback key bindings File
# DaCoda 2017
# -----------------
# Requirements:
#
# Every control group split by  ---
# Every control group name must be unique.
# Every key name must be unique.
#
# Warnings:
# Keys with the same name may cause unwanted behaviour
# Controlgroups with the same name will cause unwanted behaviour
name: global
keys:
    - name : global up
      keycodes : [UpArrow]
      modifiers : []
    - name : global down
      keycodes : [DownArrow]
      modifiers : []
    - name : global left
      keycodes : [LeftArrow]
      modifiers : []
    - name : global right
      keycodes : [RightArrow]
      modifiers : []
    - name : global mouse left
      keycodes : [Mouse0]
      modifiers : []
    - name : global mouse right
      keycodes : [Mouse1]
      modifiers : []
---
name: selection
keys:
    - name : single select
      keycodes : [Mouse0]
      modifiers : []
    - name : multi select
      keycodes : [Mouse0]
      modifiers : [LeftShift]
    - name : deselect
      keycodes : [Mouse0]
      modifiers : [Escape]
    - name : deselect all
      keycodes : [Escape]
      modifiers : []
    - name : select all
      keycodes : [A]
      modifiers : [LeftControl]
---
name: selectiondrag
keys:
    - name : drag select
      keycodes : [Mouse0]
      modifiers : []
---
name: units
keys:
    - name : unit special 1
      keycodes : [Z]
      modifiers : []
    - name : unit special 2
      keycodes : [X]
      modifiers : []
    - name : unit move
      keycodes : [Mouse1]
      modifiers : []
    - name : unit move attack
      keycodes : [Mouse1]
      modifiers : [LeftControl]
    - name : unit move sequential
      keycodes : [Mouse1]
      modifiers : [LeftShift]
    - name : unit move sequential attack
      keycodes : [Mouse1]
      modifiers : [LeftShift, LeftControl]
---
name: unit assign group
keys:
    - name : unit assign group 1
      keycodes : [Alpha1]
      modifiers : [LeftControl]
    - name : unit assign group 2
      keycodes : [Alpha2]
      modifiers : [LeftControl]
    - name : unit assign group 3
      keycodes : [Alpha3]
      modifiers : [LeftControl]
    - name : unit assign group 4
      keycodes : [Alpha4]
      modifiers : [LeftControl]
    - name : unit assign group 5
      keycodes : [Alpha5]
      modifiers : [LeftControl]
    - name : unit assign group 6
      keycodes : [Alpha6]
      modifiers : [LeftControl]
    - name : unit assign group 7
      keycodes : [Alpha7]
      modifiers : [LeftControl]
    - name : unit assign group 8
      keycodes : [Alpha8]
      modifiers : [LeftControl]
    - name : unit assign group 9
      keycodes : [Alpha9]
      modifiers : [LeftControl]
    - name : unit assign group 0
      keycodes : [Alpha0]
      modifiers : [LeftControl]
---
name: unit select group
keys:
    - name : unit select group 1
      keycodes : [Alpha1]
      modifiers : []
    - name : unit select group 2
      keycodes : [Alpha2]
      modifiers : []
    - name : unit select group 3
      keycodes : [Alpha3]
      modifiers : []
    - name : unit select group 4
      keycodes : [Alpha4]
      modifiers : []
    - name : unit select group 5
      keycodes : [Alpha5]
      modifiers : []
    - name : unit select group 6
      keycodes : [Alpha6]
      modifiers : []
    - name : unit select group 7
      keycodes : [Alpha7]
      modifiers : []
    - name : unit select group 8
      keycodes : [Alpha8]
      modifiers : []
    - name : unit select group 9
      keycodes : [Alpha9]
      modifiers : []
    - name : unit select group 0
      keycodes : [Alpha0]
      modifiers : []
---
name: camera
keys:
    - name : camera up
      keycodes : [UpArrow, W]
      modifiers : []
    - name : camera down
      keycodes : [DownArrow, S]
      modifiers : []
    - name : camera left
      keycodes : [LeftArrow, A]
      modifiers : []
    - name : camera right
      keycodes : [RightArrow, D]
      modifiers : []
    - name : camera rotate left
      keycodes : [LeftArrow]
      modifiers : [LeftControl]
    - name : camera rotate right
      keycodes : [RightArrow]
      modifiers : [LeftControl]
    - name : camera zoom in
      keycodes : [UpArrow]
      modifiers : [LeftControl]
    - name : camera zoom out
      keycodes : [DownArrow]
      modifiers : [LeftControl]